### ISSUE TITLE
"Refatorar" os assets.

### ISSUE THREAD

**Issue by vidalvasconcelos** [laravelbrasil/art#2]
@hernandev Olá, tudo bom. Eu fiz essa logo atual do laravel brasil, mas acho que posso melhorar ela, não modificar muito mais dar um retoque e também quero criar mais material para a comunidade, você pode me dar acesso a esse repositório?

**Comment by hernandev** [comment]
você agora tem acesso de administrador nesse repositório.

fique a vontade.

**Comment by vidalvasconcelos** [comment]
Obrigado @hernandev !
